name: run-unit-tests
on: [push, pull_request]
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python set up
        uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
      - name: set PYTHONPATH
        run: |
          echo "PYTHONPATH=$GITHUB_WORSPACE/core" >> $GITHUB_ENV
          echo $(pwd)
      - name: run-unit-tests
        run: pytest --ignore=tests/archive
