name: run-unit-tests
on: [push, pull_request]
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python set up
        uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: set PYTHONPATH
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE/simfarm" >> $GITHUB_ENV
          echo $(pwd)
          echo $GITHUB_ENV
      - name: run-unit-tests
        run: pytest --ignore=tests/archive
